site_name: Missouri S&T ACM
nav: 
  - Home: index.md
  - Learn About ACM: 
    - Overview: 'ACM/Overview.md'
  - Leadership:
    - Getting Started: 'Leadership/GettingStarted.md'
  - Documentation: 
    - Servers: 'ACM/Overview.md'